FROM node:18-alpine AS base
WORKDIR /app
ADD package.json .
RUN npm install ci
ADD components ./components
ADD pages ./pages
ADD styles ./styles
ADD additional.d.ts .
ADD next-env.d.ts .
ADD tsconfig.json .
ADD .env.local .
ADD postcss.config.js .
ADD tailwind.config.js .
CMD ["npm", "run", "dev"]
