# Build the Next.js application
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the application code
{{ range .Components}}
COPY {{.}} {{.}}
{{end}}

# Build the application
RUN npm run build

# Production environment
FROM node:18-alpine AS production

WORKDIR /app

COPY --from=builder /app/package.json ./package.json

# Install production dependencies only
RUN npm install --omit=dev

# Set up a non-root user
RUN adduser -D appuser
USER appuser
COPY --chown=appuser service.codefly.yaml /app/service.codefly.yaml

# Copy the built Next.js application from the builder stage
COPY --chown=appuser --from=builder /app/.next /app/.next


# Set the NODE_ENV environment variable to production
ENV NODE_ENV production


# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]
